### ISSUE TITLE
Add a "Cool Game!"/Like button.

### ISSUE THREAD

**Issue by nuclearsandwich** [blazingcloud/pie-bakery#3]
Everyone needs a little positive reinforcement. Since most kids aren't on Twitter/GitHub, you can't really tell them you had fun playing their game.

At first I thought it'd be nice to have comments on games, but the internet has some less than awesome people who could abuse that.

Instead, what if a button is added to the end of a game that just says "Thanks, that was cool!" with a little counter of how many people played. I wouldn't bother making anyone sign in, so obviously it's open to gaming. But at the end of the day, I think it's worth it to let kids know that their game was worth a chuckle.

I'd also be interested in contributing this to feature once December settles down (read: is over).

**Comment by ultrasaurus** [comment]
I was just thinking the same thing!  Would love another contributor.  We could have optional signups with email or twitter so kids or parents could get notifications, but it is important not to require that, since kids under 13 often don't have email addresses and we don't want to enable stalkers.  By the way, Pivotal Tracker is here:  https://www.pivotaltracker.com/projects/115060 -- I added this as a story :)
